### ISSUE TITLE
Heart loss cooldown config

### ISSUE THREAD

**Issue by Reflxx1** [KartoffelChipss/LifeStealZ#15]
Ive noticed that the gaining of hearts has a configurable delay however the loss of hearts is unconfigurable.

**Comment by KartoffelChipss** [comment]
I don't really see how that makes any sense. Players would be invincible in that timeframe?

**Comment by Reflxx1** [comment]
Players would still be able to die however it prevents bed trapping / spawnkilling and instantly wiping a player

**Comment by KartoffelChipss** [comment]
But would the other player still get a heart? If yes they could farm endless hearts. If no You woulnd't take any fights because you don't know if another player is on cooldown because you could loose a heart but the other person not.

The whole LifeSteal concept is a bit flawed. I think there is no one correct behavior and if I would implement each behavior for every person (what I've done before and I'm tired of it) so I'm sorry but I won't implement it. 
If you absolutely need the feature, you'll need to implement it yourself and contribute to this repo. You could also try asking abbev on the Discord server, maybe she would be happy to implement that.
