### ISSUE TITLE
Can we withdraw into our inventory?

### ISSUE THREAD

**Issue by PizzaGod873** [KartoffelChipss/LifeStealZ#35]
**Is your feature request related to a problem? Please describe.**
When trying to test, I want to be able to hold a heart.

**Describe the solution you'd like**
I don't want to withdraw to another player, I want it in my inventory.

**Describe alternatives you've considered**
I have tried other plugins, which aren't working, so I have decided to look in the code or wait.

**Comment by PizzaGod873** [comment]
My bad. wrong lifesteal plugin. This plugin doesn't even work for me.

**Comment by KartoffelChipss** [comment]
If you mean that you want the heart to be in you inventory instead of being added to your hearts when killing a player: Yes that is possible with this plugin.
If the plugin isn't working for you: It's probably that you are using Spigot or Bukkit and not PaperMC.
If you need any additional Support, please use the [Discord](https://strassburger.org/discord)
